[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 12

[window]
decorations = "None"

[mouse]
hide_when_typing = true

[general]
import = ["~/.config/alacritty/catppuccin.toml"]

